//! Auto-generated by `datalink_shim_sqlite_dynlink_emit::emit_dynlink`
//! (Phase A, opaque-blob scalar dispatch). Do NOT edit by hand — regenerate.
#![allow(unused_imports, dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "bridge",
        generate_all,
    });
}

use bindings::exports::sqlite::extension::metadata::{
    Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
};
use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
use bindings::sqlite::extension::types::{FunctionFlags, SqlValue};

use bindings::compose::dynlink::linker;

const PROVIDER_ID: &str = "postgis_core-composed";
const EXTENSION_ROOT: &str = "postgis";
const CATALOG_EXTENSION: &str = "postgis";
const CATALOG_VERSION: &str = "0.1.0";

fn resolve() -> Result<linker::Instance, String> {
    linker::resolve_by_id(&PROVIDER_ID.to_string())
        .map_err(|e| format!("dynlink resolve('{}'): {:?}", PROVIDER_ID, e))
}

// -----------------------------------------------------------
// CBOR envelope (mirrors provider crate's Request/Response).
// -----------------------------------------------------------

#[derive(Debug, Clone)]
enum CborValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<CborValue>),
}

impl serde::Serialize for CborValue {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        match self {
            CborValue::Null => s.serialize_unit(),
            CborValue::Bool(b) => s.serialize_bool(*b),
            CborValue::Int(i) => s.serialize_i64(*i),
            CborValue::Float(f) => s.serialize_f64(*f),
            CborValue::Text(t) => s.serialize_str(t),
            CborValue::Bytes(b) => s.serialize_bytes(b),
            CborValue::List(items) => {
                use serde::ser::SerializeSeq;
                let mut seq = s.serialize_seq(Some(items.len()))?;
                for item in items {
                    seq.serialize_element(item)?;
                }
                seq.end()
            }
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
struct Request {
    #[serde(rename = "v")]
    version: u32,
    args: Vec<CborValue>,
}

#[derive(Debug, Clone, serde::Deserialize)]
struct Response {
    #[serde(default)]
    ok: Option<ResponseValue>,
    #[serde(default)]
    err: Option<String>,
}

#[derive(Debug, Clone)]
enum ResponseValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<ResponseValue>),
}

impl<'de> serde::Deserialize<'de> for ResponseValue {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{Error, MapAccess, SeqAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = ResponseValue;
            fn expecting(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
                f.write_str("a CBOR value (null, bool, int, float, text, bytes, list)")
            }
            fn visit_unit<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_none<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_bool<E: Error>(self, v: bool) -> Result<ResponseValue, E> { Ok(ResponseValue::Bool(v)) }
            fn visit_i64<E: Error>(self, v: i64) -> Result<ResponseValue, E> { Ok(ResponseValue::Int(v)) }
            fn visit_u64<E: Error>(self, v: u64) -> Result<ResponseValue, E> {
                if v <= i64::MAX as u64 { Ok(ResponseValue::Int(v as i64)) }
                else { Err(E::custom("u64 overflow to i64")) }
            }
            fn visit_f64<E: Error>(self, v: f64) -> Result<ResponseValue, E> { Ok(ResponseValue::Float(v)) }
            fn visit_str<E: Error>(self, v: &str) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v.to_string())) }
            fn visit_string<E: Error>(self, v: String) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v)) }
            fn visit_bytes<E: Error>(self, v: &[u8]) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v.to_vec())) }
            fn visit_byte_buf<E: Error>(self, v: Vec<u8>) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v)) }
            fn visit_seq<A: SeqAccess<'de>>(self, mut s: A) -> Result<ResponseValue, A::Error> {
                let mut items = Vec::new();
                while let Some(v) = s.next_element::<ResponseValue>()? { items.push(v); }
                Ok(ResponseValue::List(items))
            }
            fn visit_map<A: MapAccess<'de>>(self, mut m: A) -> Result<ResponseValue, A::Error> {
                let k: Option<String> = m.next_key()?;
                let k = k.ok_or_else(|| A::Error::custom("empty map"))?;
                let v = match k.as_str() {
                    "Null" => { let _: serde::de::IgnoredAny = m.next_value()?; ResponseValue::Null }
                    "Bool" => ResponseValue::Bool(m.next_value()?),
                    "Int"  => ResponseValue::Int(m.next_value()?),
                    "Float" => ResponseValue::Float(m.next_value()?),
                    "Text" => ResponseValue::Text(m.next_value()?),
                    "Bytes" => {
                        let b: serde_bytes::ByteBuf = m.next_value()?;
                        ResponseValue::Bytes(b.into_vec())
                    }
                    "List" => ResponseValue::List(m.next_value()?),
                    other => return Err(A::Error::custom(format!("unknown tag: {}", other))),
                };
                Ok(v)
            }
        }
        d.deserialize_any(V)
    }
}

fn encode_request(args: Vec<CborValue>) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    ciborium::into_writer(&Request { version: 1, args }, &mut out)
        .map_err(|e| format!("cbor encode: {}", e))?;
    Ok(out)
}

fn decode_response(bytes: &[u8]) -> Result<Response, String> {
    ciborium::from_reader(bytes).map_err(|e| format!("cbor decode: {}", e))
}

fn call(method: &str, args: Vec<CborValue>) -> Result<ResponseValue, String> {
    let inst = resolve()?;
    let payload = encode_request(args)?;
    let bytes = inst
        .invoke(&method.to_string(), &payload)
        .map_err(|e| format!("{}: invoke: {:?}", method, e))?;
    let resp = decode_response(&bytes)?;
    if let Some(err) = resp.err {
        return Err(format!("{}: {}", method, err));
    }
    Ok(resp.ok.unwrap_or(ResponseValue::Null))
}

// -----------------------------------------------------------
// SqlValue marshalling — variant discipline per the @1.0.0
// contract. The `wit-value` arm is Phase-A-out-of-scope; the
// bridge treats it as null in both directions.
// -----------------------------------------------------------

fn sqlv_to_cbor(v: &SqlValue) -> Result<CborValue, String> {
    Ok(match v {
        SqlValue::Null => CborValue::Null,
        SqlValue::Integer(i) => CborValue::Int(*i),
        SqlValue::Real(f) => CborValue::Float(*f),
        SqlValue::Text(t) => CborValue::Text(t.clone()),
        SqlValue::Blob(b) => CborValue::Bytes(b.clone()),
        // WitValue is Phase-A-out-of-scope. Prior code silently
        // downgraded it to CBOR null, which lied to the provider
        // (an explicit-typed argument became indistinguishable
        // from a real NULL). Surface an explicit error instead so
        // callers see a diagnostic on the SQL side.
        SqlValue::WitValue(_) => {
            return Err("bridge: WitValue arg not supported in dynlink Phase A".to_string());
        }
    })
}

fn response_to_sqlv(v: ResponseValue) -> Result<SqlValue, String> {
    Ok(match v {
        ResponseValue::Null => SqlValue::Null,
        ResponseValue::Bool(b) => SqlValue::Integer(if b { 1 } else { 0 }),
        ResponseValue::Int(i) => SqlValue::Integer(i),
        ResponseValue::Float(f) => SqlValue::Real(f),
        ResponseValue::Text(t) => SqlValue::Text(t),
        ResponseValue::Bytes(b) => SqlValue::Blob(b),
        // A list-shaped response has no SQLite scalar sqlvalue
        // arm. Prior code silently returned SqlValue::Null, hiding
        // a shape mismatch behind an implicit NULL. Return an
        // explicit error so the SQL side sees a diagnostic.
        ResponseValue::List(_) => {
            return Err("bridge: list-shaped response not supported".to_string());
        }
    })
}

fn scalar_name_by_id(id: u64) -> Option<&'static str> {
    match id {
        1 => Some("st_3d_closest_point"),
        2 => Some("st_3d_contains"),
        3 => Some("st_3d_d_within"),
        4 => Some("st_3d_dwithin"),
        5 => Some("st_3d_intersects"),
        6 => Some("st_3d_line_interpolate_point"),
        7 => Some("st_3d_longest_line"),
        8 => Some("st_3d_make_box"),
        9 => Some("st_3d_max_distance"),
        10 => Some("st_3d_shortest_line"),
        11 => Some("st_3dboundary"),
        12 => Some("st_3dcentroid"),
        13 => Some("st_3dclosestpoint"),
        14 => Some("st_3dcontains"),
        15 => Some("st_3dconvexhull"),
        16 => Some("st_3ddifference"),
        17 => Some("st_3ddistance"),
        18 => Some("st_3ddwithin"),
        19 => Some("st_3denvelope"),
        20 => Some("st_3dintersection"),
        21 => Some("st_3dintersects"),
        22 => Some("st_3dlength"),
        23 => Some("st_3dlineinterpolatepoint"),
        24 => Some("st_3dlongestline"),
        25 => Some("st_3dmakebox"),
        26 => Some("st_3dmaxdistance"),
        27 => Some("st_3dperimeter"),
        28 => Some("st_3dreverse"),
        29 => Some("st_3drotate"),
        30 => Some("st_3dscale"),
        31 => Some("st_3dshortestline"),
        32 => Some("st_3dtranslate"),
        33 => Some("st_3dunion"),
        34 => Some("st_area_threed"),
        35 => Some("st_areathreed"),
        36 => Some("st_boundary_threed"),
        37 => Some("st_boundarythreed"),
        38 => Some("st_centroid_threed"),
        39 => Some("st_centroidthreed"),
        40 => Some("st_closest_point_3d"),
        41 => Some("st_closest_point_threed"),
        42 => Some("st_contains_3d"),
        43 => Some("st_contains_threed"),
        44 => Some("st_covers_threed"),
        45 => Some("st_dfully_within_threed"),
        46 => Some("st_distance_sphere"),
        47 => Some("st_distance_spheroid"),
        48 => Some("st_distance_threed"),
        49 => Some("st_distancesphere"),
        50 => Some("st_distancespheroid"),
        51 => Some("st_distancethreed"),
        52 => Some("st_dwithin_3d"),
        53 => Some("st_dwithin_threed"),
        54 => Some("st_envelope_threed"),
        55 => Some("st_envelopethreed"),
        56 => Some("st_force_threed"),
        57 => Some("st_forcethreed"),
        58 => Some("st_intersects_3d"),
        59 => Some("st_intersects_threed"),
        60 => Some("st_length_spheroid"),
        61 => Some("st_length_threed"),
        62 => Some("st_lengthspheroid"),
        63 => Some("st_lengththreed"),
        64 => Some("st_line_interpolate_point_threed"),
        65 => Some("st_longest_line_3d"),
        66 => Some("st_longest_line_threed"),
        67 => Some("st_max_distance_3d"),
        68 => Some("st_max_distance_threed"),
        69 => Some("st_perimeter_threed"),
        70 => Some("st_perimeterthreed"),
        71 => Some("st_reverse_threed"),
        72 => Some("st_reversethreed"),
        73 => Some("st_rotate_threed"),
        74 => Some("st_rotatethreed"),
        75 => Some("st_scale_threed"),
        76 => Some("st_scalethreed"),
        77 => Some("st_shortest_line_3d"),
        78 => Some("st_shortest_line_threed"),
        79 => Some("st_sym_difference_threed"),
        80 => Some("st_translate_threed"),
        81 => Some("st_translatethreed"),
        _ => None,
    }
}

/// SQL-name aliasing: translate a compact-form SQL name (e.g.
/// `st_geomfromtext`) to its WIT-canonical (long) form
/// (`st_geom_from_text`) before kebab-casing to the provider
/// method name. The catalog carries both spellings as scalars in
/// `leaf.scalars` (both are advertised via `metadata.describe()`
/// so callers can use either), and as first-class `[[aliases]]`
/// entries. The provider dispatch only matches the WIT-canonical
/// form; the bridge's per-row `call` calls `canonical_for(name)`
/// so both spellings route to the same provider arm.
fn canonical_for(name: &str) -> &str {
    match name {
            "st_3dclosestpoint" => "st_3d_closest_point",
            "st_3dcontains" => "st_3d_contains",
            "st_3d_dwithin" => "st_3d_d_within",
            "st_3ddwithin" => "st_3d_d_within",
            "st_3dintersects" => "st_3d_intersects",
            "st_3dlineinterpolatepoint" => "st_3d_line_interpolate_point",
            "st_3dlongestline" => "st_3d_longest_line",
            "st_3dmakebox" => "st_3d_make_box",
            "st_3dmaxdistance" => "st_3d_max_distance",
            "st_3dshortestline" => "st_3d_shortest_line",
            "st_areathreed" => "st_area_threed",
            "st_boundarythreed" => "st_boundary_threed",
            "st_centroidthreed" => "st_centroid_threed",
            "st_distancesphere" => "st_distance_sphere",
            "st_distancespheroid" => "st_distance_spheroid",
            "st_distancethreed" => "st_distance_threed",
            "st_envelopethreed" => "st_envelope_threed",
            "st_forcethreed" => "st_force_threed",
            "st_lengthspheroid" => "st_length_spheroid",
            "st_lengththreed" => "st_length_threed",
            "st_perimeterthreed" => "st_perimeter_threed",
            "st_reversethreed" => "st_reverse_threed",
            "st_rotatethreed" => "st_rotate_threed",
            "st_scalethreed" => "st_scale_threed",
            "st_translatethreed" => "st_translate_threed",
        other => other,
    }
}

// -----------------------------------------------------------
// Guest impls.
// -----------------------------------------------------------

struct Component;

impl MetadataGuest for Component {
    fn describe() -> Manifest {
        let scalar_functions: Vec<ScalarFunctionSpec> = vec![
            ScalarFunctionSpec {
                id: 1,
                name: "st_3d_closest_point".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 2,
                name: "st_3d_contains".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 3,
                name: "st_3d_d_within".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 4,
                name: "st_3d_dwithin".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 5,
                name: "st_3d_intersects".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 6,
                name: "st_3d_line_interpolate_point".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 7,
                name: "st_3d_longest_line".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 8,
                name: "st_3d_make_box".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 9,
                name: "st_3d_max_distance".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 10,
                name: "st_3d_shortest_line".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 11,
                name: "st_3dboundary".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 12,
                name: "st_3dcentroid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 13,
                name: "st_3dclosestpoint".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 14,
                name: "st_3dcontains".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 15,
                name: "st_3dconvexhull".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 16,
                name: "st_3ddifference".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 17,
                name: "st_3ddistance".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 18,
                name: "st_3ddwithin".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 19,
                name: "st_3denvelope".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 20,
                name: "st_3dintersection".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 21,
                name: "st_3dintersects".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 22,
                name: "st_3dlength".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 23,
                name: "st_3dlineinterpolatepoint".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 24,
                name: "st_3dlongestline".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 25,
                name: "st_3dmakebox".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 26,
                name: "st_3dmaxdistance".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 27,
                name: "st_3dperimeter".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 28,
                name: "st_3dreverse".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 29,
                name: "st_3drotate".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 30,
                name: "st_3dscale".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 31,
                name: "st_3dshortestline".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 32,
                name: "st_3dtranslate".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 33,
                name: "st_3dunion".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 34,
                name: "st_area_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 35,
                name: "st_areathreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 36,
                name: "st_boundary_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 37,
                name: "st_boundarythreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 38,
                name: "st_centroid_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 39,
                name: "st_centroidthreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 40,
                name: "st_closest_point_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 41,
                name: "st_closest_point_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 42,
                name: "st_contains_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 43,
                name: "st_contains_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 44,
                name: "st_covers_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 45,
                name: "st_dfully_within_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 46,
                name: "st_distance_sphere".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 47,
                name: "st_distance_spheroid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 48,
                name: "st_distance_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 49,
                name: "st_distancesphere".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 50,
                name: "st_distancespheroid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 51,
                name: "st_distancethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 52,
                name: "st_dwithin_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 53,
                name: "st_dwithin_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 54,
                name: "st_envelope_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 55,
                name: "st_envelopethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 56,
                name: "st_force_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 57,
                name: "st_forcethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 58,
                name: "st_intersects_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 59,
                name: "st_intersects_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 60,
                name: "st_length_spheroid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 61,
                name: "st_length_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 62,
                name: "st_lengthspheroid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 63,
                name: "st_lengththreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 64,
                name: "st_line_interpolate_point_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 65,
                name: "st_longest_line_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 66,
                name: "st_longest_line_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 67,
                name: "st_max_distance_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 68,
                name: "st_max_distance_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 69,
                name: "st_perimeter_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 70,
                name: "st_perimeterthreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 71,
                name: "st_reverse_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 72,
                name: "st_reversethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 73,
                name: "st_rotate_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 74,
                name: "st_rotatethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 75,
                name: "st_scale_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 76,
                name: "st_scalethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 77,
                name: "st_shortest_line_3d".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 78,
                name: "st_shortest_line_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 79,
                name: "st_sym_difference_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 80,
                name: "st_translate_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 81,
                name: "st_translatethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
        ];
        Manifest {
            name: EXTENSION_ROOT.to_string(),
            version: CATALOG_VERSION.to_string(),
            scalar_functions,
            aggregate_functions: vec![],
            collations: vec![],
            vtabs: vec![],
            dot_commands: vec![],
            has_authorizer: false,
            has_update_hook: false,
            has_commit_hook: false,
            has_wal_hook: false,
            wal_hook_id: 0,
            declared_capabilities: vec![],
            optional_capabilities: vec![],
            preferred_prefix: None,
            prefix_expansion: None,
            typed_values: vec![],
        }
    }
}

impl ScalarFunctionGuest for Component {
    fn call(func_id: u64, args: Vec<SqlValue>) -> Result<SqlValue, String> {
        let name = scalar_name_by_id(func_id)
            .ok_or_else(|| format!("unknown function id {}", func_id))?;
        // SQL-style null propagation. Providers that need to
        // observe explicit NULL arguments will need a follow-up
        // Phase to opt in per-arm.
        if args.iter().any(|v| matches!(v, SqlValue::Null)) {
            return Ok(SqlValue::Null);
        }
        // Alias translation: SQL name → WIT-canonical → provider
        // method (kebab-case). Compact-form SQL names (e.g.
        // `st_geomfromtext`) route through `canonical_for` to their
        // long form (`st_geom_from_text`) before kebab-casing;
        // non-alias names pass through unchanged. See
        // `canonical_for` above.
        let canonical = canonical_for(name);
        let method = canonical.replace('_', "-");
        let cbor_args: Vec<CborValue> = args
            .iter()
            .map(sqlv_to_cbor)
            .collect::<Result<Vec<_>, String>>()?;
        let resp = call(&method, cbor_args)?;
        response_to_sqlv(resp)
    }
}

bindings::export!(Component with_types_in bindings);
